### ISSUE TITLE
Search is failing on some demos

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#69] opened 2019-08-16 01:54 UTC
Doesn't throw an error, but also doesn't show any results.
Example: https://ragingstags-sscom.demo.silverstripe.cc/search?q=contact
Might be intermittent?

**Comment by dnsl48** [comment] 2019-08-19 23:59
Could be related to https://github.com/silverstripe/bambusa-installer/issues/71
Will retest this after #71 gets fixed.

**Comment by dnsl48** [comment] 2019-08-26 23:08
Caused by https://github.com/silverstripeltd/open-sourcerers/issues/129

**Comment by dnsl48** [comment] 2019-08-27 02:32
fixed (for new demos)

**Comment by dnsl48** [comment] 2019-08-27 02:34
Well... after both https://github.com/silverstripeltd/open-sourcerers/issues/129 and https://github.com/silverstripe/bambusa-installer/issues/71 are fixed, search still not showing any results (though not returning 500s anymore).
Seems like there may be another cause yet.

**Comment by dnsl48** [comment] 2019-09-09 02:42
Addressed by disabling search due to infrastructure problems
 - https://github.com/silverstripe/bambusa-installer/pull/81
 - https://github.com/silverstripe/bambusa-theme/pull/54

More details at https://silverstripe.atlassian.net/wiki/spaces/BAM/pages/813367881/Bambusa+Search+issues

**Closed as completed** 2019-10-02 01:01 UTC
Labels: bug
